### ISSUE TITLE
No Attribution

### ISSUE THREAD

**Issue by shellscape** [webschik/postcss-less#1]
Greetings

This project looks like it's a near-identical clone of https://github.com/gilt/postcss-less, which is in of itself a fork of https://github.com/postcss/postcss-scss. You've removed the LICENSE and don't have any attribution mentioned anywhere. Kindly suggesting you add attribution for one of the projects that this is based from.

**Comment by webschik** [comment]
No problem! I will add an additional info about these projects and that the current one is based on them.

**Comment by shellscape** [comment]
:+1:  cheers

**Comment by webschik** [comment]
Done :)
https://github.com/webschik/postcss-less/blob/master/README.md#appreciation
