### ISSUE TITLE
mixinsAsAtRules flag doesn't generate the correct node types

### ISSUE THREAD

**Issue by patsissons** [webschik/postcss-less#19]
in order for `stylelint` to parse the _at rules_ properly, we need to override `mixin` nodes as `atrule` nodes (which is already happening) and additionally the child node (the mixin function block) must be overriden as a `rule` node.

Currently two stylelint rule tests are failing due to this issue (both are essentially the same).

`.for(@n: 1) when (@n <= 10) { .n-@{n} #foo { } .for(@n + 1) }` with rule `selector-no-id`

the `#foo` should be detected in there and a warning should be reported.

**NOTE**: this is how the `postcss-scss` module is functioning, and I'm just reporting on how `postcss-less` is differing at the moment.

**Comment by webschik** [comment]
@patsissons, I will try to fix that on this weekend

**Comment by webschik** [comment]
Hi, @patsissons! I haven't had much time before, so I've started only today to work on this issue. 
Please, pull the project from this [branch](https://github.com/webschik/postcss-less/tree/webschik.mixins-content) and check your `Stylelint` tests. All tests for `postcss-less` are passed.

* I've added a new option [innerMixinsAsRules](https://github.com/webschik/postcss-less/blob/webschik.mixins-content/test/parser/mixins.spec.js#L28) to parse all inner mixins as Rule node.
* I've refactored part of code, so I would like to know that everything isn't broken :)

**Comment by patsissons** [comment]
I ran the `stylelint` tests against your branch and everything looks good, just the one expected failure (`function-whitespace-after`, which we aren't dealing with in this repo). Let me know when you have it merged and published to npm.

**Comment by webschik** [comment]
@patsissons, it's done. Version0.5.0 is available :)
