### ISSUE TITLE
Move dist from repo

### ISSUE THREAD

**Issue by ai** [webschik/postcss-less#2]
Good repositories avoid generated content. There is many reasons for it, but I think main reasons is:

* Some user may make mistake and fix for `dist` content.
* `dist` makes diffs much harder to read

So we should add dist to `.gitignore`

**Comment by webschik** [comment]
Thanks @ai, you're right! I've just updated ignore files

**Comment by ai** [comment]
You need to delete `dist` first.

```
git rm -R dist/
```

**Comment by webschik** [comment]
of course :) it's done.
