### ISSUE TITLE
Mixins within rules aren't added to nodes collection

### ISSUE THREAD

**Issue by shellscape** [webschik/postcss-less#22]
Consider the following input: `.foo { .mixin(); }`

And the resulting `Rule` node:

```js
Rule {
  raws: { before: '', between: ' ', after: ' .mixin(); ' },
  type: 'rule',
  nodes: [],
  parent: 
   Root {
     raws: { semicolon: false, after: '' },
     type: 'root',
     nodes: [ [Circular] ],
     source: { input: [Object], start: [Object] },
     lastEach: 1,
     indexes: {} },
  source: 
   { start: { line: 1, column: 1 },
     input: Input { css: '.foo { .mixin(); }', id: '<input css 5>' },
     end: { line: 1, column: 18 } },
  selector: '.foo',
  lastEach: 2,
  indexes: {} }
```

The `nodes` array is empty, and `node.raws.after` contains the source for the mixin declaration, but it should probably be part of the `nodes` collection as a node type.

**Comment by webschik** [comment]
@shellscape , I think it's the same problem as in https://github.com/webschik/postcss-less/issues/19

**Comment by shellscape** [comment]
Looks like it might be related, yes.

**Comment by webschik** [comment]
@shellscape, it's fixed now.
