### ISSUE TITLE
Mixins without a body, or an empty body, aren't parsed correctly

### ISSUE THREAD

**Issue by shellscape** [webschik/postcss-less#23]
This may seem silly on the surface, but this is actually valid LESS: `.foo();`. Unfortunately, postcss-less doesn't parse this mixin, rather the result is a `Root` node:

```js
Root {
  raws: { after: '.foo();' },
  type: 'root',
  nodes: [],
  source: 
   { input: Input { css: '.foo();', id: '<input css 1>' },
     start: { line: 1, column: 1 } },
  lastEach: 1,
  indexes: {} }
```

Mixins with an empty body also fail to parse correctly, and are instead parsed as a rule: `.foo(){}`

```
Rule {
  raws: { before: '', between: '', after: '' },
  type: 'rule',
  nodes: [],
  parent: 
   Root {
     raws: { semicolon: false, after: '' },
     type: 'root',
     nodes: [ [Circular] ],
     source: { input: [Object], start: [Object] },
     lastEach: 1,
     indexes: {} },
  source: 
   { start: { line: 1, column: 1 },
     input: Input { css: '.foo(){}', id: '<input css 1>' },
     end: { line: 1, column: 8 } },
  selector: '.foo()',
  lastEach: 1,
  indexes: {} }
```

**Comment by webschik** [comment]
@shellscape, yes. I've mentioned it in restrictions. Look on the [postcss parser](https://github.com/postcss/postcss/blob/master/lib/parser.es6), we couldn't parse mixins without body as rules, because postcss is looking for curly brackets for them and without brackets we will have an error `Unknown word`. Also we can't parse these mixins as declarations, because postcss parser needs colon symbol for them. Now I parse mixins without body with custom types:

````less
.foo(); //'mixin-function'
.foo; // 'mixin-inline'
````
and postcss skips them.

**Comment by webschik** [comment]
@shellscape, all mixins with body are parsed as rules or at-rules (you can configurate that).

**Comment by shellscape** [comment]
@webschik where's the documentation on the configuration that you mentioned?

**Comment by webschik** [comment]
https://github.com/webschik/postcss-less#less-transformations

See `mixinsAsAtRule` option. But now there is [some problems](https://github.com/webschik/postcss-less/issues/19), I'm working on it.

**Comment by webschik** [comment]
@shellscape, I've just released a new version with fixes and updated [ReadMe](https://github.com/webschik/postcss-less/blob/master/README.md). Probably we should keep this issue opened for future elimination of restrictions.

**Comment by webschik** [comment]
@shellscape, it's fixed now.
