### ISSUE TITLE
Getting error "rule.params.trim is not a function"

### ISSUE THREAD

**Issue by bdukes** [webschik/postcss-less#28]
When we run our less files through stylelint, we were getting an error about mixin rules.  We updated to the latest version of all our npm packages and got a different mixin rule error.  After adding your recommended postcss config (`mixinsAsAtRules: true, innerMixinsAsRules: true`), we're now getting an error that says "rule.params.trim is not a function"

It still appears to render warnings from stylelint, so I think it's more of an annoyance at the moment.

Let me know how I can help track that down, if it's not already a known issue.

**Comment by webschik** [comment]
@bdukes, thank you! This issue is related to https://github.com/webschik/postcss-less/issues/25
