### ISSUE TITLE
LESS syntax full support

### ISSUE THREAD

**Issue by webschik** [webschik/postcss-less#29]
After some discussions [1](https://github.com/webschik/postcss-less/issues/25#issuecomment-202704969), [2](https://github.com/webschik/postcss-less/pull/27#discussion_r57595491) I've decided to remove LESS-specific hacks from `postcss-less` and support full-syntax tree.

**Comment by webschik** [comment]
@patsissons could you, please, try to test [develop branch for this task](https://github.com/webschik/postcss-less/tree/webschik.less-full-syntax) by `Stylelint` tests? 
I removed some hacks and restrictions from parsing process and would like to know what's broken now and how I can fix that.

**Comment by patsissons** [comment]
i would suggest to keep developing this as you would  for full support and i'll just use my fork to create a new module for stylelint.

**Comment by webschik** [comment]
@patsissons, also I would like to support Stylelint and make `postcss-less` compatible with it, because I like this tool and would like to use it for my LESS code :) 
Does `Stylelint` need many changes to work with `postcss-less`?

**Comment by patsissons** [comment]
I'm basically just disabling some of the extra tokenization and parsing code. That's why I think a separate fork is the best way forward. I can still PR the general patches back to your repo.

**Comment by webschik** [comment]
@patsissons, okay. Maybe we should create module `stylelint-postcss-less`? Also I will drop `Stylelint` support from `postcss-less` docs, because they aren't compatible.

**Comment by webschik** [comment]
v0.7.0 with all changes is released

**Comment by patsissons** [comment]
so I went through your recent changes and your syntax tree is now probably compatible with stylelint (mostly due to the node type changes). I'm just doing some testing against stylelint now and I only have one small issue with comments that I'm trying to track down.

**Comment by patsissons** [comment]
ok i think i tracked down the issue. stylelint is looking for `comment.raws.inline` but the postcss-less parser is flagging `comment.inline`.

**Comment by webschik** [comment]
Hi, @patsissons!
Do you have any updates about `Stylelint` + `postcss-less` testing?

**Comment by patsissons** [comment]
I applied your suggested inline fix to stylelint comment linting and all tests now pass (except for the whitespace one which is currently disabled until stylelint patches it). Currently just waiting on them to merge the PR, not sure what the ETA on that is.

**Comment by webschik** [comment]
@patsissons, thank you! Could you, please, send me a link on this PR?

**Comment by patsissons** [comment]
https://github.com/stylelint/stylelint/pull/926

going to look into the `block-no-empty` stuff tomorrow morning and do a little PR cleanup.

**Comment by patsissons** [comment]
`block-no-empty` stuff is likely an issue in this module. I'll let you take a further look if you want ahead of time. Issue is that a parametric mixin (which has no block) is creating an empty `nodes` array on the node, which `stylelint` is interpreting as an empty block. I believe the `nodes` member should be not be defined in this case.

e.g., `.a { .b(1px); }`

**Comment by webschik** [comment]
@patsissons, I've made nodes as empty array according to issue https://github.com/webschik/postcss-less/issues/23.

Also check `root.first.first.ruleWithoutBody` for code above.

**Comment by patsissons** [comment]
yea i saw `ruleWithoutBody` while diagnosing the issue. I assume that is custom to `postcss-less` so I'm not sure what the best way to adapt it for `stylelint` since it expects a rule without a body to have an undefined `nodes` value.

**Comment by webschik** [comment]
@patsissons @shellscape, I think it makes sense to set nodes to `undefined`, because property `nodes` as empty array shows us a rule with empty body. In the current case we have to show that there is no body at all.

**Comment by shellscape** [comment]
I would examine how postcss proper handles this. I've found that many of the patterns in place there have been thoroughly vetted by the community.

**Comment by webschik** [comment]
@shellscape, okay, I will test it in postcss. But as I remember, `postcss` can't handle rules without body. Will see...
