### ISSUE TITLE
Nodes property for rules without body

### ISSUE THREAD

**Issue by webschik** [webschik/postcss-less#33]
@patsissons, @shellscape, I've checked `postcss-scss` parser:

```js
const root = parse('@include border-radius(10px);');
console.log(root.first.nodes); // undefined
```

So it's our case, probably it nice to have the same behaviour.

**Comment by shellscape** [comment]
Sounds good to me.

**Comment by webschik** [comment]
Okay, I'm going to fix that.

**Comment by webschik** [comment]
@patsissons, could you, please, checkout the project from [this branch](https://github.com/webschik/postcss-less/tree/webschik.fix-nodes) and run your tests?

**Comment by patsissons** [comment]
If i have some downtime today i'll take a look, but I would be shocked if 1b90762 didn't resolve the issue.

**Comment by webschik** [comment]
Okay, I hope it fix that :)

**Comment by webschik** [comment]
@patsissons, I've update `postcss-less` with above fixes.

**Comment by patsissons** [comment]
roger, i'll pull it into `stylelint` and test things out tomorrow morning.

**Comment by patsissons** [comment]
`stylelint` guys have pulled in this new version. should be published to npm in `5.5.0`.

**Comment by webschik** [comment]
@patsissons, good news :)

**Comment by diagramatics** [comment]
Just checking in with the news, so the separation between the parser and the Stylelint compatible plugin @patsissons is making is cancelled?

**Comment by webschik** [comment]
@diagramatics yes! And Stylelint supports `postcss-less` from version 5.3

**Comment by diagramatics** [comment]
That's awesome! I'll try this out again and report back if something unexpected occurs. Thanks so much!

**Comment by shellscape** [comment]
@webschik @diagramatics I'm confused by recent comments. Is postcss-less going to remain an agnostic syntax for postcss, or it is a syntax only meant for use in stylelint?

**Comment by webschik** [comment]
@shellscape , `postcss-less` is a LESS parser in general and supports full LESS syntax. It works in common PostCss way, for example as postcss-scss. And it's not a Stylelint plugin. Guys from Stylelint fixed compatibility issues with postcss-less and Stylelint uses now this parser

**Comment by patsissons** [comment]
That is correct, in general `stylelint` supports `postcss-less` but may have some false positives for certain things that `stylelint` doesn't properly support (yet). My initial concept of a `stylelint` specific version was abandoned now that compatibility is very good between the two.
