### ISSUE TITLE
Parsing escaped string fails if the property is in a nested selector

### ISSUE THREAD

**Issue by diagramatics** [webschik/postcss-less#35]
This is quite an edge case, but consider this:

```less
@testVar: 10px;

.test-wrap {
    .selector {
        height: calc(~"100vh - @{testVar}");
    }
}
```

This will throw an error with this stack trace:
```
CssSyntaxError: /dir/test.less:5:106: Unclosed quote
    at Input.error (/dir/node_modules/postcss/lib/input.js:61:22)
    at unclosed (/dir/node_modules/stylelint/node_modules/postcss-less/dist/tokenizer/unclosed.js:8:23)
    at tokenizeQuotes (/dir/node_modules/stylelint/node_modules/postcss-less/dist/tokenizer/tokenize-quotes.js:24:36)
    at tokenizeSymbol (/dir/node_modules/stylelint/node_modules/postcss-less/dist/tokenizer/tokenize-symbol.js:74:42)
    at lessTokenize (/dir/node_modules/stylelint/node_modules/postcss-less/dist/less-tokenize.js:48:38)
    at LessParser.tokenize (/dir/node_modules/stylelint/node_modules/postcss-less/dist/less-parser.js:51:54)
    at lessParse (/dir/node_modules/stylelint/node_modules/postcss-less/dist/less-parse.js:22:12)
    at new LazyResult (/dir/node_modules/postcss/lib/lazy-result.js:61:24)
    at Processor.process (/dir/node_modules/postcss/lib/processor.js:34:16)
    at lintString (/dir/node_modules/stylelint/dist/standalone.js:97:9)
```

If you take `.selector` out of `.test-wrap` it won't fail parsing.

**Comment by webschik** [comment]
@diagramatics, what versions of `Stylelint` and `postcss-less` are you using?

**Comment by diagramatics** [comment]
`Stylelint`'s at `5.4.0` and `postcss-less` at `0.9.0`.

**Comment by webschik** [comment]
@diagramatics, please, check [my example](http://code.runnable.com/Vx0nPC-MWr8LDVQy/postcss-less-35-for-node-js). Parsing looks fine.

**Comment by diagramatics** [comment]
Okay, that does look fine. I've run the same settings again with a higher Stylelint version `6.2.2` but with the smallest snippet I can extract out of my real code:

```less
.test {
    .another-test {
        anything: function(~"@{variable}");
    }
}

.test-test {
    anything: function(~"@{test}");
}

```

I've noticed patterns on how the code breaks.
* It's a mixin or a real function in LESS. Replacing `function()` with `calc()`  or `.mixin()` produces the same result.
* It has to have the `~` string interpolation (?) and a variable used in it.
* It breaks when you have the usage of `function(~"@{something}")` in a nested level of `n` and another function call with a string interpolation in a nested nevel of `n-1`. Nesting the first call 3 levels deep and the next one 1 level deep doesn't do this error.

This error is very specific and that's what I can pinpoint from just doing trial and errors. Sorry if I can't give you more help in this, haven't had time debugging this properly with `node-debug`.

**Comment by webschik** [comment]
@diagramatics, thank you for investigation! :) I will check that and fix.

**Comment by webschik** [comment]
@patsissons, I've just fixed the bug posted by @diagramatics. Could you, please, run your Stylelint tests with `postcss-less` from branch  https://github.com/webschik/postcss-less/tree/webschik.35.escaped-string ?

**Comment by webschik** [comment]
@diagramatics, I've fixed that in version 0.10. It seems like I should create a task for Stylelint team to update a postcss-less version.

**Comment by patsissons** [comment]
yea please create an issue in stylelint, i won't have a chance to test this out for a while.

**Comment by webschik** [comment]
https://github.com/stylelint/stylelint/issues/1179

**Comment by jeddy3** [comment]
FYI, `stylelint@6.3.1` contains the new `postcss-less` version.

**Comment by webschik** [comment]
@jeddy3, great! Thank you!

**Comment by diagramatics** [comment]
Seems like 0.10.0 has fixed it. Thanks a lot for the hard work!
