### ISSUE TITLE
Mixins aren't parsed correctly 

### ISSUE THREAD

**Issue by ChrisEbert** [webschik/postcss-less#38]
I'm still having an issue like in #23. My mixin `.mix() {color: red}` results in `.mix(){}` when it is called in some selector.

```
postcss().process('.mix() {color: red} .selector {.mix()}', {
    syntax: postcssLess
}).then(function (result) {
    console.log(result.content); // .mix() {color: red}.selector {.mix(){}}
});
```
Do I have to set any further postcss configuration?

**Comment by webschik** [comment]
Hi!

If you would like to have a result as 

```less
.mix() {color: red} 
.selector {color: red}
```
that's not possible, because `postcss-less` is just a parser that convert LESS code to `PostCSS` syntax tree.

**Comment by ChrisEbert** [comment]
Hi!

Yes I know.
I was expecting:
```
.mix() {color: red}
.selector {.mix()}
```

But i got:
```
.mix() {color: red}
.selector {.mix(){}}
```

Do you see the difference?

**Comment by webschik** [comment]
@ChrisEbert , yep :) I will try to update custom stringifier in `postcss-less` that considers a propert [ruleWithoutBody](https://github.com/webschik/postcss-less#rulerulewithoutbody)

**Comment by roelvanduijnhoven** [comment]
I'm having this as well. Any luck so far @webschik? 

Example, though it is kinda similar:

```less
.rotation(@deg:5deg){
  .transform(rotate(@deg));
}
```

Gets translated into:
```less
.rotation(@deg:5deg){
  .transform(rotate(@deg)){}
}
```

Great initiative building LESS syntax! Thanks.

**Comment by webschik** [comment]
@roelvanduijnhoven, thanks for your example :) I don't have much time now, but I'm going to fix that in few days.

**Comment by roelvanduijnhoven** [comment]
Thanks. Keep me posted! Otherwise would be willing to look at this myself. But I would need some help on where to look. Let me now.

**Comment by webschik** [comment]
Hi guys! 

Try to update `postcss-less` to v. 0.11.0 and use its own [stringifier](https://github.com/webschik/postcss-less#stringifier).

**Comment by roelvanduijnhoven** [comment]
Our designers are grateful they won't ever have to vendor prefix again! Thank you.

**Comment by ChrisEbert** [comment]
Works just perfect! Thank you. :+1:
