### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by ai** [webschik/postcss-less#4]
Users afraid that done third-party's parser could brake user's sources. This is why good integration tests are highly recommended.

In PostCSS default parser I use Github and Twitter styles. In save parser I use browserhacks styles.

I think you should ask Less team for some integration tests. Smoke test will be enough - just parse all they tests sources without a errors.

**Comment by webschik** [comment]
I use the style cases from `postcss-parser-tests` and my own test cases. They cover a big part of user flows.
