### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by paazmaya** [webschik/postcss-less#41]
In order to see what had changed between npm releases, please use git tags.

For example

```sh
git tag v0.9.0 feee3c86e50543f44c25609216c78e6e941e8224
git tag v0.10.0 fcb9afaa30c2808431674e9bf331e6bc06171e77
git tag v0.11.0 c3474e3ed0780b53b32432e31caa1d7ade348236
```
... and so forth

**Comment by webschik** [comment]
@paazmaya, good advice! Thank you :)

**Comment by paazmaya** [comment]
@webschik You are welcome! By the way, could you also set the previous tags, few of which I tried to collect to the above commands?

**Comment by webschik** [comment]
@paazmaya, I'm going to do that! :)
