### ISSUE TITLE
Keep changelog up to date

### ISSUE THREAD

**Issue by jeddy3** [webschik/postcss-less#44]
We're currently using `0.10.0` in stylelint, but we've got [a pending PR](https://github.com/stylelint/stylelint/pull/1281) to update to `0.12.0`. It doesn't look like the changelog has been updated since `0.3.0`, so it's a bit tricky for us to quickly verify what has changed between the releases. If possible, can you add some (back-dated) release notes to the changelog? And can you update it before each release?

I'm not sure if you'll find it useful, but we use [`npmpub`](https://github.com/MoOx/npmpub) to help with the stylelint releases. It uses the changelog to tag (which will help with https://github.com/webschik/postcss-less/issues/41), release and publish a new version. There's other automated tooling out there as well too :)

**Comment by webschik** [comment]
@jeddy3, you're right. I didn't have much time for Changelog, so now it's quite uncontrolled :) From v0.12.0 I've started to use Git tags and I'm going to write Changelog for each release. v.0.12.0 have important bug fixes, so, please upgrade Stylelint dependency to that.

**Comment by jeddy3** [comment]
> From v0.12.0 I've started to use Git tags and I'm going to write Changelog for each release

Thank you :)

>  v.0.12.0 have important bug fixes, so, please upgrade Stylelint dependency to that.

Will do.
