### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by nicothin** [webschik/postcss-less#7]
i use my sass expirience: https://gist.github.com/nicothin/65b836e9eec28a3aa080/9b6243db0f89a1a34ea3af3846178fa3d4af338e
but is not working: https://gist.github.com/nicothin/65b836e9eec28a3aa080#gistcomment-1715127
is working: https://gist.github.com/nicothin/65b836e9eec28a3aa080/2abfeaa8257ee3197daaefe78611f3d4d84e94fd
something is wrong?

**Comment by webschik** [comment]
It's the same problem as https://github.com/webschik/postcss-less/issues/7

**Comment by nicothin** [comment]
problem #7 - is problem #7? )))
